
<div class="bx--col-xs-12 bx--col-md-6 bx--col-lg-4 section-3col--card">
    <div class="card-sm">

      <div class="card-img image card-half">
        <div class="img-container--icon" style="background-image: url(<?php the_field($theBG); ?>)">
            <img class="icon" src="<?php echo get_field($theImageS); ?>"/>
            <div class="overlay"></div>
        </div>
      </div>

      <div class="card-content card-half">
        <div class="text-container">
          <h3><?php the_field($theHeadingS);?></h3>
          <p>
            <?php the_field($theParagrafS);?>
          </p>
        </div>
      </div>

    </div>



</div>
