
<div class="bx--col-xs-12 bx--col-md-6 bx--col-lg-4 section-3col--card">
    <div class="card-sm">

      <div class="card-img image card-half">
        <div class="img-container">
          <img class="featured-image" src="<?php echo get_field($theImage); ?>"/>
        </div>
      </div>

      <div class="card-content card-half">
        <div class="text-container">
          <h3><?php the_field($theHeading);?></h3>
          <p>
            <?php the_field($theParagraf);?>
          </p>
        </div>
      </div>

    </div>


</div>
