<div class="sendify">
  <div class="sendify-container">
    <div class="sendify-text">
      <h4 class="bx--type-gamma"><?php the_field('sendify_cta_heading', 'option');?></h4>
      <p class="bx--type-epsilon">
        <?php the_field('sendify_cta_paragraf', 'option');?>
      </p>
    </div>

    <a href="https://www.sendify.se" target="_blank"><button class="bx--btn bx--btn--secondary-white" type="button"><?php the_field('sendify_btn_label', 'option');?></button></a>

  </div>

</div>
