<?php

// vars
$contact = get_field('contact_section', 'option');

if( $contact ): ?>

  <div class="fw--grid bg-01">
    <div class="fw--row">

        <div class="fw--col-sm-12 fw--col-md-6 section-fw inrush">
            <div class="inrush-text">
              <h4><?php echo $contact['subheading']; ?></h4>
              <h2 class="bx--type-alpha"><?php echo $contact['phone_number']; ?></h2>
            </div>
        </div>

        <div class="fw--col-sm-12 fw--col-md-6 section-fw contactform">
          <h4><?php echo $contact['form_subheading']; ?></h4>
          <?php echo do_shortcode( '[contact-form-7 id="621" title="Contact form 1" html_class="bx--form-item"]' ); ?>
        </div>

    </div>
  </div>

<?php endif; ?>
