
  <div id="tab-panel-1" class="tab-1" role="tabpanel" aria-labelledby="tab-link-1" aria-hidden="false">
    <div class="services bg-02 section-default">

        <div class="bx--grid">
          <div class="bx--row">

            <?php

            $args = array(
            'post_type' => 'post',
            'posts_per_page' => -1,
            'orderby' => 'post_date',
            'order' => 'DESC'
          );
            // The Query
            $query = new WP_Query( $args );

            // The Loop
            if ( $query->have_posts() ) {
            	while ( $query->have_posts() ) {
            		$query->the_post();

                include( get_template_directory() . '/phtml-components/cards/card-sm.phtml');

            	}
            	/* Restore original Post Data */
            	wp_reset_postdata();
            } else {
            }

            ?>

          </div>

        </div>

    </div>
  </div>
