
<?php $i = 0;
      foreach( $terms as $term ):
      $number = ++$i;?>

    <div id="tab-panel-<?= $number;?>" class="tab-<?= $number;?>" role="tabpanel" aria-labelledby="tab-link-<?= $number;?>" aria-hidden="false " hidden>
      <div class="services bg-02 section-default">

          <div class="bx--grid">
            <div class="bx--row">

              <?php
              $id = $term->term_id;

              if ($term->slug == 'nyheter'){

                $args = array(
                  'post_type' => 'post',
                  'posts_per_page' => -1,
                  // 'cat' => $id,
                  'orderby' => 'post_date',
                  'order' => 'DESC'
                 );
              } else if ($term->slug == 'populart'){

                $args = array(
                  'posts_per_page' => -1,
                  'meta_key' => 'post_views_count',
                  'orderby' => 'meta_value_num',
                  'order' => 'DESC'
                );
              } else {

                $args = array(
                  'post_type' => 'post',
                  'posts_per_page' => -1,
                  'cat' => $id,
                  'orderby' => 'post_date',
                  'order' => 'DESC'
                 );
              }

              // The Query
              $query = new WP_Query( $args );

              if ( $query->have_posts() ) {
                while ( $query->have_posts() ) {
                  $query->the_post();
                  // echo getPostViews(get_the_ID()); // Prove views
                  include( get_template_directory() . '/phtml-components/cards/card-sm.phtml');

                }
                /* Restore original Post Data */
                wp_reset_postdata();
              } else {
              }

              ?>

            </div>

          </div>

      </div>
    </div>
  <?php endforeach;?>
