<nav data-tabs class="bx--tabs tabnav" role="navigation">
  <div class="bx--tabs-trigger" tabindex="0">
    <a href="javascript:void(0)" class="bx--tabs-trigger-text" tabindex="-1"></a>
    <svg width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
      <path d="M10 0L5 5 0 0z"></path>
    </svg>
  </div>
  <ul class="bx--tabs__nav bx--tabs__nav--hidden" role="tablist">
    <li id="tab-1" class="bx--tabs__nav-item bx--tabs__nav-item--selected" data-target=".tab-1" role="presentation">
      <a id="tab-link-1" class="bx--tabs__nav-link" href="javascript:void(0)" role="tab" aria-controls="tab-panel-1" aria-selected="true">Most Recent</a>
    </li>
    <li id="tab-2" class="bx--tabs__nav-item" data-target=".tab-2" role="presentation">
      <a id="tab-link-2" class="bx--tabs__nav-link" href="javascript:void(0)" role="tab" aria-controls="tab-panel-2" aria-selected="false">News</a>
    </li>
    <li id="tab-3" class="bx--tabs__nav-item" data-target=".tab-3" role="presentation">
      <a id="tab-link-3" class="bx--tabs__nav-link" href="javascript:void(0)" role="tab" aria-controls="tab-panel-3" aria-selected="false">Infographics</a>
    </li>
    <li id="tab-4" class="bx--tabs__nav-item" data-target=".tab-4" role="presentation">
      <a id="tab-link-4" class="bx--tabs__nav-link" href="javascript:void(0)" role="tab" aria-controls="tab-panel-4" aria-selected="false">Webinars</a>
    </li>
    <li id="tab-5" class="bx--tabs__nav-item" data-target=".tab-5" role="presentation">
      <a id="tab-link-5" class="bx--tabs__nav-link" href="javascript:void(0)" role="tab" aria-controls="tab-panel-5" aria-selected="false">E-books</a>
    </li>
  </ul>
</nav>
