<?php

    if (get_the_ID( $page_for_posts )) {
        $terms = get_field('choose_categories', $page_for_posts);
    } else {
        $terms = get_field('choose_categories');
    }

    if( $terms ): ?>
    <nav data-tabs class="bx--tabs tabnav" role="navigation">
      <div class="bx--tabs-trigger" tabindex="0">
        <a href="javascript:void(0)" class="bx--tabs-trigger-text" tabindex="-1"></a>
        <svg width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
          <path d="M10 0L5 5 0 0z"></path>
        </svg>
      </div>
      <ul class="bx--tabs__nav bx--tabs__nav--hidden" role="tablist">
        <?php foreach( $terms as $term ):
              $number = ++$i;?>
        <li id="tab-<?= $number;?>" class="bx--tabs__nav-item bx--tabs__nav-item--selected" data-target=".tab-<?= $number;?>" role="presentation">
          <a id="tab-link-<?= $number;?>" class="bx--tabs__nav-link" href="<?= '#'.$term->slug;?>" role="tab" aria-controls="tab-panel-<?= $number;?>" aria-selected="true"><?= $term->name;?></a>
        </li>
  <?php endforeach;
        endif;?>

  </ul>
</nav>
