<?php

// vars
$services = get_field('our_services');

if( $services ): ?>
<div class="bx--grid section-default">

      <div class="bx--row section-center--col">
        <h6 class="revealer-0"><?= $services['subheading']; ?></h6>
        <h3 class="bx--type-beta revealer-100"><?= $services['heading']; ?></h3>
      </div>


<?php endif; ?>

<?php

$posts = get_field('service_cards');

if( $posts ): ?>


  <div class="bx--row">
    <?php foreach( $posts as $post): // variable must be called $post (IMPORTANT) ?>
        <?php setup_postdata($post);

              $serviceurl = $post->post_name;?>



          <div class="bx--col-xs-12 revealer-100">

              <a class="card-link" href="<?= the_permalink(86) . '#' . $serviceurl ?>">

                <div class="card-lg interactive">

                    <div class="card-img image card-half">
                      <div class="img-container">
                        <img class="featured-image" src="<?php the_post_thumbnail_url(); ?>"/>
                      </div>
                    </div>

                    <div class="card-content card-half">
                      <div class="text-container">
                        <h3><?= the_title();?></h3>
                        <p><?= excerpt(30);?></p>
                      </div>
                      <div class="btn-container">
                        <button class="bx--btn bx--btn--primary" type="button">Read More</button>
                      </div>

                    </div>

                </div>

              </a>

          </div>
    <?php endforeach; ?>
        </div>
</div>

    <?php wp_reset_postdata(); // IMPORTANT - reset the $post object so the rest of the page works correctly ?>
<?php endif; ?>
