<div class="services bg-02 section-default">

  <div class="bx--grid">
    <div class="bx--row section-center--col">
      <h6 class="revealer-0"><?php the_field('services_subheading');?></h6>
      <h3 class="bx--type-beta revealer-100"><?php the_field('services_heading');?></h3>
    </div>
  </div>

    <div class="bx--grid">
      <div class="bx--row">
        <?php
        $args = array(
            'post_parent' => 86,
            'post_type' => 'page',
            'orderby' => 'menu_order',
            'posts_per_page' => 3
        );

        $child_query = new WP_Query( $args );
        ?>

        <?php while ( $child_query->have_posts() ) : $child_query->the_post();

            include( get_template_directory() . '/phtml-components/cards/card-lg.phtml');

        endwhile; ?>

        <?php
        wp_reset_postdata();?>

      </div>

    </div>

</div>
