<div class="countries">


    <div class="country">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
    </div>

    <div class="country">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
    </div>

    <div class="country">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
    </div>

    <div class="country">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
    </div>

</div>


<!-- <div class="bx--grid bg-03 section-0rem countries">
  <div class="bx--row">

    <div class="bx--col-xs-12 bx--col-sm-4 section-4col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
      </div>
    </div>

    <div class="bx--col-xs-12 bx--col-sm-4 section-4col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
      </div>
    </div>

    <div class="bx--col-xs-12 bx--col-sm-4 section-4col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
      </div>
    </div>

    <div class="bx--col-xs-12 bx--col-sm-4 section-4col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
      </div>
    </div>

  </div>
</div> -->
