<?php if( get_field($city_one) ): ?>

<div class="bx--grid bg-03 section-2rem">
  <div class="bx--row">
    <div class="bx--col-xs-12 bx--col-sm-4 section-3col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_one;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_one;?></h4>
      </div>
    </div>
    <div class="bx--col-xs-12 bx--col-sm-4 section-3col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_two;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_two;?></h4>
      </div>
    </div>
    <div class="bx--col-xs-12 bx--col-sm-4 section-3col">
      <div class="col--flexcenter cities">
        <h6 class="revealer-0"><?=$city_three;?></h6>
        <h4 class="bx--type-gamma revealer-100"><?=$hours_three;?></h4>
      </div>
    </div>
  </div>
</div>
<?php endif; ?>
