<div class="hero hero-sm" style="background-image: url(
  <?php if ( is_page(20) ) {
            echo get_field('hero_image');

        } elseif ( is_home() ) { // Learn without latest post as bg image
            echo get_field('hero_image',get_option('page_for_posts'));

        } else { // Posts get thumbnail image as bg image
            $bg_thumbnail = get_the_post_thumbnail_url(get_the_ID(),'full');
            echo $bg_thumbnail;
        }
      ?>

  )">
  <div class="overlay"></div>


    <div class="bx--col-xs-12 bx--col-md-12 hero-content">
      <?php if ( is_singular('post') ) :?>
            <h2 class="bx--type-beta type-white">
      <?php else :?>
            <h2 class="bx--type-giga type-white">
      <?php endif;?>
          <?php if ( get_the_ID() == 86 ) {

                } elseif ( is_home() ) {
                  echo get_field('hero_heading',get_option('page_for_posts'));

                } else {
                  echo esc_html( get_the_title() );
                }
              ?>
        </h2>
    </div>
</div>
