<?php

// vars
$hero = get_field('hero');

if( $hero ): ?>
<div class="hero home hero-lg" style="background-image: url(<?php the_field('image');?>">
    <div class="bx--col-xs-12 bx--col-md-12 hero-content">

        <h6 class="bx--type-delta type-white"><?php echo $hero['subheading']; ?></h6>
        <h2 class="bx--type-giga type-white"><?php echo $hero['heading']; ?></h2>

        <button class="bx--btn bx--btn--secondary-white modal" type="button"><?php echo $hero['label']; ?></button>

        <div class="scrolldown">
            <a class="scrolldown-link" id="services" href="#"><?php echo $hero['scroll_link']; ?></a>
            <svg class="scrolldown-arrow" width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
              <path d="M10 0L5 5 0 0z"></path>
            </svg>
        </div>

    </div>
    <div class="hero-video">
      <div class="overlay"></div>
      <video autoplay muted loop class="hero-video--video">
        <source src="http://localhost:8888/wp-content/uploads/2018/02/hero-truck.mp4" type="video/mp4">
      </video>
    </div>

</div>

<a name="services"/>

<?php endif; ?>
