<div data-modal id="nofooter" class="bx--modal">
  <div class="bx--modal-container">
    <div class="bx--modal-header">
      <p class="bx--modal-header__label bx--type-delta"><?php the_field('modal_subheading', 'options');?></p>
      <p class="bx--modal-header__heading bx--type-beta"><?php the_field('modal_phonenumber', 'options');?></p>
      <button class="bx--modal-close" type="button" data-modal-close data-modal-primary-focus aria-label="close modal">
        <svg class="bx--modal-close__icon" width="10" height="10" viewBox="0 0 10 10" fill-rule="evenodd">
          <title>Close Modal</title>
          <path d="M9.8 8.6L8.4 10 5 6.4 1.4 10 0 8.6 3.6 5 .1 1.4 1.5 0 5 3.6 8.6 0 10 1.4 6.4 5z"></path>
        </svg>
      </button>
    </div>

    <div class="bx--modal-content">
      <p><?php the_field('modal_paragraf', 'options');?></p>
      <?php echo do_shortcode( '[contact-form-7 id="647" title="Contact Form - Modal"]' ); ?>

    </div>
  </div>
</div>
