<nav class="navbar-mobile start">
  <!--left section -->
  <div class="navbar-left">
    <a href="/"><img class="eds-logo" src="<?php echo get_stylesheet_directory_uri(); ?>/icons/eds-logo--white.png" /></a>
  </div>

  <!--right section-->
  <div class="navbar-right">
  <!-- Hamburger Icon -->
  <div class="hamburger">
    <div class="hamburger-line line-1"></div>
    <div class="hamburger-line line-2"></div>
    <div class="hamburger-line line-3"></div>
  </div>

  </div>

</nav>
