
<div class="blog">


  <!-- Slider main container -->
  <div class="swiper-container">
      <!-- Additional required wrapper -->
      <div class="swiper-wrapper">


        <?php

        $args = array(
        'post_type' => 'post',
        'posts_per_page' => 5,
        'orderby' => 'post_date',
        'order' => 'DESC'
      );


        // The Query
        $query = new WP_Query( $args );

        // The Loop
        if ( $query->have_posts() ) {
        	while ( $query->have_posts() ) {
        		$query->the_post();

            include( get_template_directory() . '/phtml-components/blog/blog--post.phtml');


        	}
        	/* Restore original Post Data */
        	wp_reset_postdata();
        } else {
        }

        ?>

    </div>
    <div class="blog-pagination swiper-pagination"></div>

  </div>

  <div class="blog-btn-prev"><img class="arrow--prev" src="<?php echo get_stylesheet_directory_uri(); ?>/icons/icn-arrow.svg"?></div>
  <div class="blog-btn-next"><img class="arrow--next" src="<?php echo get_stylesheet_directory_uri(); ?>/icons/icn-arrow.svg"?></div>

</div>
