<div class="swiper-slide">
  <div class="fw--grid">
    <div class="fw--row">

      <div class="fw--col-sm-12 fw--col-md-6 blog-content">
        <div class="blog-text-container">
          <h6>LEARN</h6>
          <h3 class="bx--type-beta"><?php echo the_title();?></h3>
          <p>
          <?php echo excerpt(30);?>
          </p>
        </div>
        <div class="btn-container">
          <a href="/index.php?page_id=13"><button class="bx--btn bx--btn--secondary" type="button"><?php the_field('blog_btn_secondary_label');?></button></a>
          <a href="<?php the_permalink();?>"><button class="bx--btn bx--btn--primary" type="button"><?php the_field('blog_btn_label');?></button></a>
        </div>

      </div>
      <div class="fw--col-sm-12 fw--col-md-6 blog-image" style="background-image: url(<?php the_post_thumbnail_url(); ?>"></div>

      <!-- <div class="fw--col-sm-12 fw--col-md-6 blog-image">
          <div class="img-container">
            <img class="featured-image" src="<?php the_post_thumbnail_url(); ?>"/>
          </div>
      </div> -->
    </div>

  </div>

</div>
