<?php

// $i = 0;
//
// $service = new WP_Query( array( 'post_type' => 'service', 'posts_per_page' => -1 ) );
// $faq = new WP_Query( array( 'post_type' => 'faq', 'posts_per_page' => -1 ) );?>

  <div id="tab-panel-1" class="tab-1" role="tabpanel" aria-labelledby="tab-link-1" aria-hidden="false">

    <div class="section-2rem">
        <?php


        $faq_main_heading = get_field('faq_main_heading');

        $selectservice = get_field('select_service');

        if ($selectservice == 'industry_automotive'):
        ?>

        <?php
            // check if the flexible content field has rows of data
            if( have_rows('flexible_content_service') ):

                 // loop through the rows of data
                while ( have_rows('flexible_content_service') ) : the_row();

                    if( get_row_layout() == 'intro_section' ):

                      $intro = get_sub_field('intro_paragraph'); ?>

                      <div class="bx--grid section-default">
                        <div class="bx--row row--center">
                          <div class="bx--col-xs-12 bx--col-md-8 bx--col-lg-6 section-1col"><p><?= $intro;?></p></div>
                        </div>
                      </div>


                  <?php elseif ( get_row_layout() == 'split_section' ):

                      $image = get_sub_field('image');
                      $alttext = get_sub_field('image_alt_text');
                      $heading = get_sub_field('heading');
                    	$paragraph = get_sub_field('paragraph'); ?>

                      <!--SECOND PARAGRAF SECTION-->
                      <div class="fw--grid bg-01">
                        <div class="fw--row">

                          <div class="fw--col-md-6 fw--col-sm-12 section-fw bg-img" alt="<?=$alttext;?>" style="background-image: url(<?=$image;?>"></div>
                          <div class="fw--col-md-6 fw--col-sm-12 section-fw ">
                            <h3 class="bx--type-beta revealer-0"><?=$heading;?></h3>
                            <p class="revealer-100"><?=$paragraph;?></p>
                          </div>

                        </div>
                      </div>

                  <?php

            else :

                alert('no flexible found');

            endif;

             ?>


    </div>
  </div>
