<?php

    $page_for_posts = get_option( 'page_for_posts' );

    $terms = get_field('choose_categories', $page_for_posts);

    if ( is_home() ) {
        $terms = get_field('choose_categories', $page_for_posts);
    } else {
        $terms = get_field('choose_categories');
    }

    if( $terms ): ?>
    <?php if ( get_the_ID() == 517 ):?>
      <nav data-tabs class="bx--tabs tabnav industry" role="navigation">
    <?php elseif ( get_the_ID() == 86 ):?>
      <nav data-tabs class="bx--tabs tabnav transport" role="navigation">
    <?php else:?>
      <nav data-tabs class="bx--tabs tabnav" role="navigation">
    <?php endif;?>
      <div class="bx--tabs-trigger" tabindex="0">
        <a href="javascript:void(0)" class="bx--tabs-trigger-text" tabindex="-1"></a>
        <svg width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
          <path d="M10 0L5 5 0 0z"></path>
        </svg>
      </div>
      <ul class="bx--tabs__nav bx--tabs__nav--hidden" role="tablist">

        <?php
        $i = 0;
        foreach( $terms as $term ):

          if ( is_home() ) {
              $href = $term->slug;
              $name = $term->name;
          } else {
              $href = $term->post_name;
              $name = $term->post_title;
          }

          $number = ++$i;?>
          <?php if ( get_the_ID() == 517 ):?>
            <li id="tab-<?= $number;?>" class="bx--tabs__nav-item" data-target=".tab-<?= $number;?>" role="presentation">
              <a id="tab-link-<?= $number;?>" class="bx--tabs__nav-link" href="<?= '#'.$href;?>" role="tab" aria-controls="tab-panel-<?= $number;?>" aria-selected="true" hidden><?= $name ?></a>
            </li>
          <?php elseif ( get_the_ID() == 86 ):?>
            <li id="trans-tab-<?= $number;?>" class="bx--tabs__nav-item" data-target=".tab-<?= $number;?>" role="presentation">
              <a id="tab-link-<?= $number;?>" class="bx--tabs__nav-link" href="<?= '#'.$href;?>" role="tab" aria-controls="tab-panel-<?= $number;?>" aria-selected="true" hidden><?= $name ?></a>
            </li>
          <?php else:?>
            <li id="tab-<?= $number;?>" class="bx--tabs__nav-item" data-target=".tab-<?= $number;?>" role="presentation">
              <a id="tab-link-<?= $number;?>" class="bx--tabs__nav-link" href="<?= '#'.$href;?>" role="tab" aria-controls="tab-panel-<?= $number;?>" aria-selected="true" hidden><?= $name ?></a>
            </li>
          <?php endif;?>


  <?php endforeach;
        endif;?>

  </ul>
</nav>
