<?php if( have_rows('advantages') ): ?>

  <div class="bx--grid section-default bg-03">
    <div class="bx--col-xs-12 bx--col-md-12 bx--col-lg-12 section-1col"><h3 class="bx--type-beta"><?= get_sub_field('heading'); ?></h3></div>
  <div class="bx--row">

	<?php while( have_rows('advantages') ): the_row();?>
        <?php

      // check if the repeater field has rows of data
      if( have_rows('cards') ):

       	// loop through the rows of data
          while ( have_rows('cards') ) : the_row();
          ?>

              <div class="bx--col-xs-12 bx--col-md-6 bx--col-lg-4 section-3col--card">

              <div class="card-sm">
                    <div class="card-img image card-half">
                      <div class="img-container--icon">
                          <img class="icon" alt="<?= get_sub_field('alt_text');?>" src="<?= get_sub_field('icon');?>"/>
                          <div class="overlay"></div>
                      </div>
                    </div>

                    <div class="card-content card-half">
                      <div class="text-container">
                        <h3><?= get_sub_field('sub-heading');?></h3>
                        <p><?= get_sub_field('paragraph');?></p>
                      </div>
                    </div>
                </div>
              </div>


        <?php  endwhile;

      else :

          // no rows found

      endif;

      ?>


	<?php endwhile; ?>



<?php endif; ?>
</div>
</div>
