<div class="advantages bg-03 section-default">

  <div class="bx--grid">
    <div class="bx--row section-center--col">
      <h6 class="revealer-0"><?php the_field('advantages_subheading');?></h6>
      <h2 class="revealer-100"><?php the_field('advantages_heading');?></h2>
    </div>
  </div>

    <div class="bx--grid">
      <div class="bx--row">

        <?php
        $file = get_template_directory() . '/phtml-components/cards/card-sm--inactive.phtml';
        $theHeading = array('advantage_one_heading', 'advantage_two_heading', 'advantage_three_heading');
        $theParagraf = array('advantage_one_paragraf', 'advantage_two_paragraf', 'advantage_three_paragraf');
        $theImage = array('advantage_one_image', 'advantage_two_image', 'advantage_three_image');


        function includeAdvantage($file, $theHeading, $theParagraf, $theImage) {
            include($file);
        }

        echo includeAdvantage($file, $theHeading[0], $theParagraf[0], $theImage[0]);
        echo includeAdvantage($file, $theHeading[1], $theParagraf[1], $theImage[1]);
        echo includeAdvantage($file, $theHeading[2], $theParagraf[2], $theImage[2]);

        ?>

      </div>

    </div>

</div>
