<div class="bx--grid section-default bg-02">
  <div class="bx--col-xs-12 bx--col-md-12 bx--col-lg-12 section-1col"><h3 class="bx--type-beta"><?=$section_three_mainheading;?></h3></div>

  <div class="bx--row">

    <?php

    echo includeAdvantageS($file, $theHeading[0], $theParagraf[0], $theImage[0], $theBG[0]);
    echo includeAdvantageS($file, $theHeading[1], $theParagraf[1], $theImage[1], $theBG[1]);
    echo includeAdvantageS($file, $theHeading[2], $theParagraf[2], $theImage[2], $theBG[2]);

    ?>

  </div>
</div>
