<nav data-tabs class="bx--tabs tabnav transport" role="navigation">
  <div class="bx--tabs-trigger" tabindex="0">
    <a href="javascript:void(0)" class="bx--tabs-trigger-text" tabindex="-1"></a>
    <svg width="10" height="5" viewBox="0 0 10 5" fill-rule="evenodd">
      <path d="M10 0L5 5 0 0z"></path>
    </svg>
  </div>

  <ul class="bx--tabs__nav bx--tabs__nav--hidden" role="tablist">
    <li id="tab-1" class="bx--tabs__nav-item" data-target=".tab-1" role="presentation">
      <a id="tab-link-1" class="bx--tabs__nav-link" href="#dedicated-road" role="tab" aria-controls="tab-panel-1" aria-selected="false">Dedicated Road</a>
    </li>
    <li id="tab-2" class="bx--tabs__nav-item" data-target=".tab-2" role="presentation">
      <a id="tab-link-2" class="bx--tabs__nav-link" href="#dedicated-air" role="tab" aria-controls="tab-panel-2" aria-selected="false">Dedicated Air</a>
    </li>
    <li id="tab-3" class="bx--tabs__nav-item" data-target=".tab-3" role="presentation">
      <a id="tab-link-3" class="bx--tabs__nav-link" href="#dedicated-courier" role="tab" aria-controls="tab-panel-3" aria-selected="false">Dedicated Courier</a>
    </li>
  </ul>
</nav>
